### ISSUE TITLE
Headers aren't copied to $FAIRSHIPRUN/include when performing localBuild

### ISSUE THREAD

**Issue by olantwin** [ShipSoft/FairShip#155]
When using aliBuild C++ headers are copied to `$FAIRSHIP_ROOT/include`, however when using `./localBuild.sh` this does not happen (neither to `$FAIRSHIPRUN/include`, nor to `$FAIRSHIP_ROOT/include`). This makes writing compiled C++ code depending on `FairShip` headers very tedious, especially if makefiles etc. are supposed to work for `lxplus` and for `aliBuild` installations.

**Comment by ThomasRuf** [comment]
only aliBuild is supported
