### ISSUE TITLE
Refactor to use new FairLogger interfaces

### ISSUE THREAD

**Issue by olantwin** [ShipSoft/FairShip#208]
We should move to the new FairLogger interfaces, as the old ones are going to be removed.

This will likely require introducing some custom SHiP verbosities as well, to show file location by default, as `MESSAGE_ORIGIN` does not seem to be available. See [here](https://github.com/FairRootGroup/FairLogger#3-verbosity).

~Wrapping the `LOG(VERBOSITY)` statements for python also will need some work (I have a prototype...).~ Update: Due to @JLTastet's hard work, we now have a python logging interface (see #303 and #305).

Help of course welcome!

**Comment by ThomasRuf** [comment]
done for new FairRoot version
