### ISSUE TITLE
six is a required dependencies

### ISSUE THREAD

**Issue by siscia** [ShipSoft/FairShip#243]
It seems like we need the python module `six` that however is not installed in Python-modules.

**Comment by siscia** [comment]
Relevant PR https://github.com/ShipSoft/shipdist/pull/27

**Comment by olantwin** [comment]
While we could probably use it in the transition to python3, I don't think it's depended on right now. Am I missing something?

**Comment by ThomasRuf** [comment]
import six exists in pythia_conf_utils.py

**Comment by siscia** [comment]
Indeed over here: https://github.com/ShipSoft/FairShip/blob/master/python/pythia8_conf_utils.py#L5

**Comment by olantwin** [comment]
I see.

One could easily avoid this dependency to be honest, as it's only used once.

But as `six` would be quite helpful in the transition anyway, there's no harm in adding the dependency now.

**Comment by siscia** [comment]
`six` is been added! https://github.com/ShipSoft/shipdist/pull/30
