### ISSUE TITLE
Some nutau volumes use medium vacuum instead of air

### ISSUE THREAD

**Issue by antonioiuliano2** [ShipSoft/FairShip#254]
Dear FairShip experts,

checking the geometry implementation of the scattering and neutrino detector, I have noticed that some volumes use 'vacuum' as medium (see for example volTarget). However, the cave medium is air, not vacuum, as built by python/shipDet_conf.py.

Should I change the medium in these volumes, in order to better reproduce cave medium?

Best regards,
Antonio Iuliano

**Comment by ThomasRuf** [comment]
Maybe using a volume is the wrong approach. If you only need an object which contains other volumes, an assembly might be the better option. 

thomas

**Comment by antonioiuliano2** [comment]
Dear Thomas,

thank you very much for your advice, you actually pointed me to the recommended way to address these situations

However, since I have followed the wrong volume approach until now, I am going to need some time to check where all the virtual volumes are and replace them with assemblies (both in nutau and charmdet folder, at this point).

I will contact you as soon as I have any update.
Best regards,
Antonio Iuliano

**Comment by antonioiuliano2** [comment]
Thank you for your advice,
I have just opened a pull request with these changes
