### ISSUE TITLE
Future and builtins module missing in lxplus

### ISSUE THREAD

**Issue by antonioiuliano2** [ShipSoft/FairShip#260]
Dear FairShip experts,

after the application of the automatic tools `futurize` and `autopep8` for the transition to python3 (https://github.com/ShipSoft/FairShip/pull/255), the scripts do not work anymore on lxplus due to missing modules `future` and `builtins`. 

Should these modules be added to python-modules.sh, or should the commit be reverted instead?

Best regards,
Antonio Iuliano

**Comment by siscia** [comment]
Hi,

what are you doing to build FairShip?

I believe we should have those two modules in the SHiP-2020 version, is that reasonable?

Cheers,
Simone

**Comment by ThomasRuf** [comment]
yes, this is very much reasonable. The branch ship-2018 should not have the modifications of Antonio.
cheers,
Thomas

**Comment by siscia** [comment]
@antonioiuliano2 are you working agains the SHiP-2020 version (which is the master branch) or against the SHiP-2018 branch?

**Comment by antonioiuliano2** [comment]
Dear Simone,
I am working in the master branch.

**Comment by siscia** [comment]
Very well.

Now the point is a little complex. ROOT does not support the use of two version of python at the same time (yet, eventually maybe it will, but not in the very short term). So, either you compile the code for PY2 or for PY3.

PY3 still have some issue somewhere that I am investigating between today and tomorrow. As soon as those are figure out we can move to PY3 completely.

In the meantime, I would like you to be able to work easily.

Either send me an email so we can talk directly or please explain how you are building the software, so we can figure out together the best way for you to hook those dependencies!

**Comment by antonioiuliano2** [comment]
Thank you for your explanation.

I can already work easily in my local installations (where I have just added these two modules myself). The point is, the already built software in lxplus (the one I can access with FairShip/localBuild.sh) cannot run anymore these two scripts due to the missing modules.

That is, I would assume anyone with the master version currently will probably encounter the same issue when working from the lxplus local installation.

**Comment by siscia** [comment]
This should now be fixed on the latest 2020 installation in cvmfs.

I tested it myself, but if you could confirm and close the issue it would be appreciated.

Remember to source the latest folder:
```
source /cvmfs/ship.cern.ch/SHiP-2020/latest/setUp.sh
```

Cheers,

**Comment by antonioiuliano2** [comment]
Hi Simone,

I can confirm that now the modules are imported correctly and the macro works. Thank you very much for this solution!

Best regards,
Antonio Iuliano
