### ISSUE TITLE
/TMCParticleStatus.h:51:7: error: reference to 'Info' is ambiguous

### ISSUE THREAD

**Issue by ThomasRuf** [ShipSoft/FairShip#263]
trying to run FairShip run_simScript.py on openstack, ship-slc7.cern.ch with CVMFS recipe for SHiP-2020 gives:

In file included from /cvmfs/ship.cern.ch/SHiP-2020/2019/August/1/sw/slc7_x86-64/ROOT/v6-18-00_FAIRSHIP-1/include/TMCManager.h:26:
/cvmfs/ship.cern.ch/SHiP-2020/2019/August/1/sw/slc7_x86-64/ROOT/v6-18-00_FAIRSHIP-1/include/TMCParticleStatus.h:51:7: error: reference to 'Info' is ambiguous
      Info("Print", "Status of track");
      ^
/cvmfs/ship.cern.ch/SHiP-2020/2019/August/1/sw/slc7_x86-64/ROOT/v6-18-00_FAIRSHIP-1/include/TError.h:58:13: note: candidate found by name lookup is 'Info'
extern void Info(const char *location, const char *msgfmt, ...)
            ^
/cvmfs/ship.cern.ch/SHiP-2020/2019/August/1/sw//slc7_x86-64/pythia/v8230-ship-1/include/Pythia8/Info.h:30:7: note: candidate found by name lookup is 'Pythia8::Info'
class Info {
      ^
Error in <TInterpreter::AutoParse>: Error parsing payload code for class TVirtualMC with content:

#line 1 "libVMC dictionary payload"

#define _BACKWARD_BACKWARD_WARNING_H
// Inline headers
#include "TGeoMCGeometry.h"
#include "TMCAutoLock.h"
#include "TMCOptical.h"
#include "TMCParticleType.h"
#include "TMCProcess.h"
#include "TMCtls.h"
#include "TMCVerbose.h"
#include "TVirtualMCApplication.h"
#include "TVirtualMCGeometry.h"
#include "TVirtualMC.h"
#include "TVirtualMCSensitiveDetector.h"
#include "TVirtualMCStack.h"
#include "TMCManager.h"
#include "TMCManagerStack.h"
#include "TGeoMCBranchArrayContainer.h"
#include "TMCParticleStatus.h"

#undef  _BACKWARD_BACKWARD_WARNING_H

In file included from libVMC dictionary payload:17:
In file included from /cvmfs/ship.cern.ch/SHiP-2020/2019/August/1/sw/slc7_x86-64/ROOT/v6-18-00_FAIRSHIP-1/include/TMCManager.h:26:
/cvmfs/ship.cern.ch/SHiP-2020/2019/August/1/sw/slc7_x86-64/ROOT/v6-18-00_FAIRSHIP-1/include/TMCParticleStatus.h:51:7: error: reference to 'Info' is ambiguous
      Info("Print", "Status of track");
      ^
/cvmfs/ship.cern.ch/SHiP-2020/2019/August/1/sw/slc7_x86-64/ROOT/v6-18-00_FAIRSHIP-1/include/TError.h:58:13: note: candidate found by name lookup is 'Info'
extern void Info(const char *location, const char *msgfmt, ...)
            ^
/cvmfs/ship.cern.ch/SHiP-2020/2019/August/1/sw//slc7_x86-64/pythia/v8230-ship-1/include/Pythia8/Info.h:30:7: note: candidate found by name lookup is 'Pythia8::Info'
class Info {
      ^
Error in <TInterpreter::AutoParse>: Error parsing payload code for class TVirtualMCStack with content:

#line 1 "libVMC dictionary payload"

#define _BACKWARD_BACKWARD_WARNING_H
// Inline headers
#include "TGeoMCGeometry.h"
#include "TMCAutoLock.h"
#include "TMCOptical.h"
#include "TMCParticleType.h"
#include "TMCProcess.h"
#include "TMCtls.h"
#include "TMCVerbose.h"
#include "TVirtualMCApplication.h"
#include "TVirtualMCGeometry.h"
#include "TVirtualMC.h"
#include "TVirtualMCSensitiveDetector.h"
#include "TVirtualMCStack.h"
#include "TMCManager.h"
#include "TMCManagerStack.h"
#include "TGeoMCBranchArrayContainer.h"
#include "TMCParticleStatus.h"

#undef  _BACKWARD_BACKWARD_WARNING_H

Calling addVMCFields
Creating field map called MainSpecMap using /home/trufship/ShipBuild-2020/sw/slc7_x86-64/FairShip/master-1/files/MainSpectrometerField.root
ShipBFieldMap::readMapFile() creating field MainSpecMap using file /home/trufship/ShipBuild-2020/sw/slc7_x86-64/FairShip/master-1/files/MainSpectrometerField.root
x limits: -600.0000000, 600.0000000, dx = 10.0000000
y limits: -700.0000000, 700.0000000, dy = 10.0000000
z limits: -1000.0000000, 1000.0000000, dz = 10.0000000
Offsets: x = 0.0000000, y = 0.0000000, z = 3068.0000000
Angles : phi = 0.0000000, theta = 0.0000000, psi = 0.0000000
Total number of bins = 3429261; Nx = 121, Ny = 141, Nz = 201
Creating field map called NuMap using /home/trufship/ShipBuild-2020/sw/slc7_x86-64/FairShip/master-1/files/nuTauDetField.root
ShipBFieldMap::readMapFile() creating field NuMap using file /home/trufship/ShipBuild-2020/sw/slc7_x86-64/FairShip/master-1/files/nuTauDetField.root
x limits: -300.0000000, 300.0000000, dx = 8.8235292
y limits: -175.0000000, 175.0000000, dy = 5.0000000
z limits: -360.0000000, 360.0000000, dz = 10.5882349
Offsets: x = 0.0000000, y = 0.0000000, z = -3050.0000000
Angles : phi = 0.0000000, theta = 0.0000000, psi = 0.0000000
Total number of bins = 338031; Nx = 69, Ny = 71, Nz = 69
Adding field MainSpecMap
Adding field NuMap
Setting the Global field
Adding field TotalField to Global
[INFO] FairMCApplication::InitGeometry: 0

GammaToMuPair:  gamma->mu+mu- Bethe Heitler process, SubType= 15
        good cross section parametrization from 422.633 MeV to 1e+12 GeV for all Z.

AnnihiToMuPair:  e+e->mu+mu- annihilation, atomic e- at rest, SubType=.6
        threshold at 43.6931 GeV good description up to 1000 TeV for all Z.
@@@ G4ParticleHPInelastic instantiated for particle neutron data directory variable is G4NEUTRONHPDATA pointing to /cvmfs/ship.cern.ch/SHiP-2020/2019/August/1/sw//slc7_x86-64/GEANT4/v10.3.2-1/share/Geant4-10.3.2/data/G4NDL4.5/Inelastic
=======================================================================
======       Pre-compound/De-excitation Physics Parameters     ========
=======================================================================
Type of pre-compound inverse x-section              3
Type of de-excitation inverse x-section             3
Min excitation energy (keV)                         0.01
Level density (1/MeV)                               0.1
Time limit for long lived isomeres (ns)             1e+12
Use new data files                                  1
Use complete data files                             0
Correlated gamma emission flag                      0
=======================================================================
Number of de-excitation channels                    8
 PYTHIA Warning in Pythia::check: not quite matched particle energy/momentum/mass

**Comment by siscia** [comment]
Another issue in ROOT: https://root-forum.cern.ch/t/root-and-pythia8-info-symbol-found-twice/35413/12

Does it affect your results though?

**Comment by ThomasRuf** [comment]
it does not affect the results, I think, HOWEVER, if you have a program which reports about so many errors / warnings, people either loose confidence in the code, or start to ignore such messages in general and miss important messages.
I have not understood, is the fix something we can do on our side, or do we need to change some dependent code?

cheers,
Thomas

**Comment by siscia** [comment]
I agree!
No is something must be done on the ROOT side.

**Comment by ThomasRuf** [comment]
in the past, I cloned ROOT to shipsoft, modified it and used this version. Happened almost any time when we changed to a new root version.

**Comment by olantwin** [comment]
Going back to our own fork to add some patches is probably the easiest way to do it with alibuild.

We should however try to return to the official git repository of ROOT as they're not needed anymore.

Alternatively, as soon as the ROOT team has a fix, we could move to that commit in their repo until it becomes part of an official release.

@siscia Is there a JIRA ticket to follow?

**Comment by siscia** [comment]
I agree!

The simplest thing would be to just use our own fork, but in the long term we should try to stick to ROOT version...

No, no ticket.

**Comment by siscia** [comment]
Unfortunately, I wasn't able to find a reasonable way to fix this problem.

I am not quite sure what is the best way forward, maybe survive with this warning until we don't migrate to the new FairRoot logger.

**Comment by siscia** [comment]
Got it!

https://github.com/root-project/root/commit/bba421940c2073430ac03126e8f41e334e014c36

**Comment by ThomasRuf** [comment]
With the help of Simone, the issue is fixed. Removed using namespage Pythia8 in all files, and changed code to work explicitly with Pythia8::

**Comment by olantwin** [comment]
Maybe we should try not to use `using namespace bla;` if it can be avoided in general?
Looking through our code, we use `std` and `ShipUnit` in a lot of places and in at least one instance `TMath`.

Explicitly using e.g. `using std::cout;` could avoid issues in future. Especially between `TMath` and other namespaces conflicts could appear (and maybe without breaking compilation in the case of common mathematical functions).

While it's probably not urgent, it's something we should keep in mind when adding new code or touching new code.
