### ISSUE TITLE
getGeoInformation.py broken with new build

### ISSUE THREAD

**Issue by ThomasRuf** [ShipSoft/FairShip#264]
python $FAIRSHIP/macro/getGeoInformation.py -g geofile_full.conical.Pythia8-TGeant4.root  
ImportError: No module named builtins 

while with old build:
python $FAIRSHIP/macro/getGeoInformation.py -g ../geofile_full.conical.MuonBack-TGeant4.root 
Info in <TGeoManager::CloseGeometry>: Geometry loaded from file...
...

**Comment by siscia** [comment]
This should be addressed now as #260
