### ISSUE TITLE
Python 3 migration

### ISSUE THREAD

**Issue by JLTastet** [ShipSoft/FairShip#278]
Python 2 is reaching its end of life at the end of this year: https://pythonclock.org/

As discussed on the mailing list and at the SHiP software meeting, FairShip will progressively transition to Python 3, while maintaining Python 2.7 compatibility for now. This means, among other things, that new contributions must be compatible with both Python 2.7 and 3.6+.

The goal of this meta-issue is to track the required changes to make the existing code-base compatible with both Python 2 and 3.

Changes should target the `master` branch. Please try to keep the commits and PRs small enough to make reviewing them easier.

List of Python 3-related PRs:

- [x] #272 
- [x] #273 
- [x] #275 
- [x] #279 
- [x] #280 
- [x] #281 
- [x] #282 
- [x] #283 
- [x] #284 
- [x] #285 
- [x] #291 
- [x] #292 
- [x] #293 
- [x] #294 

#274 is kept as a reference, but should not be merged.

Roadmap:
- [x] Replace hard tabs by spaces.
- [x] Replace `print` statements by `print_function`.
- [x] Fix pickler.
- [x] Non-`print` Stage 1 changes.
- [x] Separate real divisions from integer divisions.
- [x] Non-division Stage 2 changes.

Division-related PRs:

- [x] #275: physics models.

List of stage 2 fixtures which do not need to be run anymore:
- [x] `basestring`
- [x] `dict`
- [x] `exec`
- [x] `getcwdu`
- [x] `input`
- [x] `itertools`
- [x] `itertools_imports`
- [x] `filter`
- [x] `long`
- [x] `map`
- [x] `nonzero`
- [x] `operator`
- [x] `raw_input`
- [x] `zip`
- [x] `cmp`
- [x] `division_safe`
- [x] `execfile`
- [x] `future_builtins`
- [x] `future_standard_library`
- [x] `future_standard_library_urllib`
- [x] `metaclass`
- [x] `newstyle`
- [x] `object`
- [x] `unicode_keep_u`
- [x] `xrange_with_import`

**Comment by JLTastet** [comment]
I will now proceed with the other stage 1 changes.

**Comment by JLTastet** [comment]
Opened #283 with the remaining stage 1 changes (mostly `d.has_key(k)` --> `k in d` and `<>` --> `!=`).

Once it is tested and merged and the pickler issue is figured out, we can proceed to identify the places where integer division is used.

**Comment by JLTastet** [comment]
Opened #284 to wrap iterators in `list()` where needed (+ a few other `dict` fixes). Please review.

**Comment by JLTastet** [comment]
Opened #285 to make use of Python 3's `range`.

**Comment by ThomasRuf** [comment]
What are the next steps, or are we finished with the Python3 transition?
thomas

**Comment by JLTastet** [comment]
Sorry, I was busy with another project last week.

I would say that right now the next step would be to figure out the integer vs. real division issue.

There are also some non-division-related  fixes needed here and there, which I can probably handle (I have some of them locally).

**Comment by ThomasRuf** [comment]
OK. I can take care about integer division in the reco/analysis/event display related scripts.

**Comment by ThomasRuf** [comment]
practical question. In run_simScript, I fixed the division issue, ship_geo.NuTauTarget.xdim/2 -> ship_geo.NuTauTarget.xdim/2. , ship_geo.NuTauTarget.xdim is a float and will ever be a float. If I commit my change, how do we keep track for which files the integer vs. real division issue is fixed?

**Comment by JLTastet** [comment]
If the issue is fixed in a file (all integer divisions have been made explicit using `//`), you should be able to add `from __future__ import division` at the top without changing anything.

Then we can just look for this line to keep track of our progress.

**Comment by ThomasRuf** [comment]
yes, this is in principle a good idea. Only side effect, it requires adding from __future__ import division  also for files which do not even have a division.

**Comment by JLTastet** [comment]
Hmm... I see. Let me think a bit.

**Comment by JLTastet** [comment]
I just checked Simone's PR again, and 73 files out of 117 should be modified as far as division is concerned. We can use `fgrep` to count how many files contain the line. Then I can `fgrep` the remaining files to make sure they do not contain any division.

Also, I think `futurize -wn --fix=division_safe **/*.py` will become a no-op when we are done. We can use this as a final check.

Alternatively, we can add the line everywhere, to make sure that future contributions behave the same on Python 2.7 and 3. This would be necessary if we are to support both versions simultaneously for `SHiP-2020`.

**Comment by ThomasRuf** [comment]
OK. Let us add the line, then we know this file had been checked.

**Comment by antonioiuliano2** [comment]
Dear all,

along with @owtscharenko , we noticed that the python/ShipGeoConfig.py script has still a module which cannot be imported in python3: cPickle

https://askubuntu.com/questions/742782/how-to-install-cpickle-on-python-3-4

I am sorry I cannot fix this myself, but I am not yet familiar with python3 modules, therefore I could not propose a good solution to replace it.

Best regards,
Antonio Iuliano

**Comment by ThomasRuf** [comment]
The solution can be found in #270, 

https://github.com/ShipSoft/FairShip/pull/270/files#diff-ec323772d1402fecac2da3ba56e7ab16

**Comment by JLTastet** [comment]
I have some more Python 3 fixes in the pipeline (all the remaining stage 2 fixes which are neither divisions nor standard library).

But #290 currently prevents me from testing them. Can anyone have a look at it?

**Comment by JLTastet** [comment]
I have opened PR's for basically all remaining non-division stage 2 changes.

Do not merge them yet. They will need some testing and review (now on both Python 2 and 3!)

**Comment by JLTastet** [comment]
> I have opened PR's for basically all remaining non-division stage 2 changes.
> 
> Do not merge them yet. They will need some testing and review (now on both Python 2 and 3!)

I think #291 can be merged now.

**Comment by JLTastet** [comment]
Closing this issue, since most of FairShip is now compatible with Python 3 (in addition to Python 2.7). Further incompatibilities should be reported as bugs.
