### ISSUE TITLE
Realistic Hadron Absorber field is never turned on

### ISSUE THREAD

**Issue by shir994** [ShipSoft/FairShip#329]
Basically, from what I can see [here] (https://github.com/ShipSoft/FairShip/blob/9e1bc80aafdec7a43726117c05796662ab3f8cb1/python/geomGeant4.py#L158), where the realistic field is loaded and in ship geo file, [here] (https://github.com/ShipSoft/FairShip/blob/9e1bc80aafdec7a43726117c05796662ab3f8cb1/geometry/geometry_config.py#L408), realistic field can be never turned on, since `c.hadronAbsorber.WithConstField` is always `True`.
I have checked quickly, and its looks like I am right, but would like to make sure it is so with @ThomasRuf.

**Comment by ThomasRuf** [comment]
you are right, it should be
  if muShieldDesign > 9:  c.hadronAbsorber.WithConstField =  False 
   else:  c.hadronAbsorber.WithConstField = True

**Comment by ThomasRuf** [comment]
fixed with https://github.com/ShipSoft/FairShip/pull/365
