### ISSUE TITLE
Build with Ubuntu 20.04

### ISSUE THREAD

**Issue by ThomasRuf** [ShipSoft/FairShip#347]
Here my experience using a fesh ISO image. 
1) the following system packages need to be installed:
sudo apt-get install libglu1-mesa libglu1-mesa-dev libx11-dev libxpm-dev libxext-dev libx11-dev libxft-dev bzip2  libbz2-dev byacc krb5-user  libkrb5-dev gfortran bison  flex libx11-dev libxml2-dev cmake libcurl4-openssl-dev  autoconf  libtool libtool-bin environment-modules

2) for python:
sudo apt install python3-pip
sudo pip3 install matplotlib numpy scipy certifi ipython ipywidgets ipykernel notebook metakernel pyyaml sklearn

3) lhapdf5 needs to be updated for python3. Created branch v5.9.1-ship3. Don't know how to make this to work also with python2. For the moment, you need to git clone lhapdf5 and change branch manually.

4) root does not have vmc automatically build these days. modified montecarlo/CMakeLists.txt, removed -if(vmc). Better solution would be to do this with shipdist, switching on option for VMC. If somebody knows how to do this?

5) fairroot, MbsAPI/CMakeLists.txt, missing include(CheckSymbolExists): committed and pushed to  May30-ship

6) alpaca does not build: cannot open output file bin/alpaca: No such file or directory. Probably something wrong in CMake file.  Disabled in fairship.sh for the moment until fix found.  

run_simScript works. Continue now checking reco and event display.

**Comment by olantwin** [comment]
6. Has been fixed in Atakan's PR which is waiting for a merge: <https://github.com/ShipSoft/shipdist/pull/42>

**Comment by olantwin** [comment]
3. Since we don't use the lhapdf5 python interface directly, an alternative is to force lhapdf5 to use python2 during it's build. I can make a PR for that solution.

4. I think we can explicitly enable it in the ROOT recipe using `-Dvmc=ON`
Quote form the ROOT 6.18 release notes:
> Deprecated packages
>
>The Virtual Monte Carlo (VMC) interfaces have been deprecated for this release and will be removed in a future release. It is no longer built by default, but can still be enabled with the option -Dvmc=ON in the CMake configuration phase. A standalone version of VMC is being developed at https://github.com/vmc-project/vmc to replace the deprecated version in ROOT.

**Comment by ThomasRuf** [comment]
alpaca issue fixed.

does anybody know why my ROOT build takes more than 15GB? all in interpreter/llvm 14.9GB!

**Comment by ThomasRuf** [comment]
-Dvmc=ON looks like a red hering, we already have:
        -Dbuiltin_vdt=ON                                          \
        -Dvmc=ON                                                  \
        ${PYTHON_ROOT:+-DPYTHON_EXECUTABLE=$PYTHONHOME/bin/python} \

**Comment by olantwin** [comment]
ALICE doesn't have a VMC aliBuild package yet, so we will probably have to create our own based on the installation instructions: <https://vmc-project.github.io/installation/vmc/>

Could we enable shipdist issues to track tasks like this?

Concerning the ROOT size, no idea...

**Comment by olantwin** [comment]
> -Dvmc=ON looks like a red hering, we already have:
> -Dbuiltin_vdt=ON
> -Dvmc=ON
> ${PYTHON_ROOT:+-DPYTHON_EXECUTABLE=$PYTHONHOME/bin/python} \

This might be a bug. I'll ask on the ROOT mattermost... The release-notes for 6.20 don't mention VMC.

**Comment by ThomasRuf** [comment]
Error in <TStreamerInfo::Build>: UpstreamTaggerHit, discarding: const double* mom, no [dimension] 
???

**Comment by ThomasRuf** [comment]
studying the million lines long root build output:
CMake Deprecation Warning at cmake/modules/RootBuildOptions.cmake:383 (message):
  >>> Option 'vmc' is deprecated and will be removed in the next release of
  ROOT.  Please contact root-dev@cern.ch should you still need it.
Call Stack (most recent call first):
  CMakeLists.txt:121 (include)

**Comment by olantwin** [comment]
On my system ROOT v6.20.4 has vmc (only minor changes to the recipe which should not be related, see <https://github.com/ShipSoft/shipdist/pull/45>), so this seems to be some Ubuntu specific problem. Which CMake do you use?

**Comment by olantwin** [comment]
> Error in TStreamerInfo::Build: UpstreamTaggerHit, discarding: const double* mom, no [dimension]
> ???

I suggest we make a new issue for this. When does this occur?

**Comment by olantwin** [comment]
> alpaca issue fixed.
> 
> does anybody know why my ROOT build takes more than 15GB? all in interpreter/llvm 14.9GB!

About 3.1 GB for me.

**Comment by ThomasRuf** [comment]
on vmc: Yes, ROOT v6-20-04 has vmc, but its use is disabled. It is only possible to switch it on by changing the cmake file.

on TStreamerInfo: this appears when running ShipReco. Since it was not reported earlier, thought it is related to new ubuntu, new root. 

on root size: I think in the past, this was related to using debug option. However, unable to find out if it is build with debug option, in principle, should not.

**Comment by olantwin** [comment]
> on vmc: Yes, ROOT v6-20-04 has vmc, but its use is disabled. It is only possible to switch it on by changing the cmake file.

Sorry if I was unclear: without changing the CMake file, vmc is built as it should be for me (on Fedora 30 and 31) with ROOT 6.20.04 when setting `-Dvmc=ON`, so there has to be more to this issue than just the ROOT version.

**Comment by shir994** [comment]
At what point during build does vmc problem arise? What package could not compile without it?

**Comment by olantwin** [comment]
It's currently a sub-package of ROOT, so part of the ROOT build. You can check whether it was built by looking at `root-config --features`.

**Comment by shir994** [comment]
I confirm that on my Ubuntu 20.04 vmc was build by default, without changing CmakeList
```cxx11 asimage builtin_afterimage builtin_clang builtin_davix builtin_ftgl builtin_gl2ps builtin_glew builtin_llvm builtin_lz4 builtin_pcre builtin_tbb builtin_vdt builtin_xxhash builtin_zstd clad dataframe davix exceptions gdml http imt mathmore mlp minuit2 opengl pyroot pythia6 pythia8 roofit rpath runtime_cxxmodules shared soversion ssl tmva tmva-cpu tmva-pymva spectrum vmc vdt x11 xml xrootd
```

**Comment by ThomasRuf** [comment]
Maybe it is an issue with CMake. What version do you have? I have 3.16.3. And do you also get many warnings and errors in the root log file?

  >>> Option 'vmc' is deprecated and will be removed in the next release of
  ROOT.  Please contact root-dev@cern.ch should you still need it.
Call Stack (most recent call first):
  CMakeLists.txt:121 (include)

CMake Deprecation Warning at cmake/modules/CheckCompiler.cmake:106 (message):
  Options cxx11/14/17 are deprecated.  Please use CMAKE_CXX_STANDARD instead.
Call Stack (most recent call first):
  CMakeLists.txt:123 (include)

**  Environment variable GSL_ROOT is set to:

    /home/truf/SHiPBuild/sw/ubuntu2004_x86-64/GSL/v1.16_FAIRSHIP-1

  For compatibility, CMake is ignoring the variable.
Call Stack (most recent call first):
  cmake/modules/SearchInstalledSoftware.cmake:454 (find_package)
  CMakeLists.txt:168 (include)
....

**Comment by ThomasRuf** [comment]
adding to ROOT CMakeLists.txt: cmake_policy(SET CMP0074 OLD) removes many of the above warnings/errors.

**Comment by ThomasRuf** [comment]
any idea why this fails:

2020-05-05@08:57:05:DEBUG:FairShip:ROOT:0: -- Performing Test found_stdstringview
2020-05-05@08:57:05:DEBUG:FairShip:ROOT:0: -- Performing Test found_stdstringview - Failed

CHECK_CXX_SOURCE_COMPILES("#include <string_view>
  int main() { char arr[3] = {'B', 'a', 'r'}; std::string_view strv(arr, sizeof(arr)); return 0;}" found_stdstringview)

**Comment by ThomasRuf** [comment]
Because std::string_view is only available from C++17 onwards. 
what c++ are we using? do we need to specify -std=c++17 in the build options?

**Comment by ThomasRuf** [comment]
going to try with, package: defaults-fairship
env:
  CXXFLAGS: "-fPIC -g -O2 -std=c++17"

**Comment by olantwin** [comment]
> Maybe it is an issue with CMake. What version do you have? I have 3.16.3. And do you also get many warnings and errors in the root log file?

I use the the CMake version from shipdist.

> > > > Option 'vmc' is deprecated and will be removed in the next release of
> > > > ROOT.  Please contact [root-dev@cern.ch](mailto:root-dev@cern.ch) should you still need it.
> > > > Call Stack (most recent call first):
> > > > CMakeLists.txt:121 (include)
> 
> CMake Deprecation Warning at cmake/modules/CheckCompiler.cmake:106 (message):
> Options cxx11/14/17 are deprecated. Please use CMAKE_CXX_STANDARD instead.

This I fixed in <https://github.com/ShipSoft/shipdist/pull/45>

**Comment by olantwin** [comment]
> Because std::string_view is only available from C++17 onwards.
> what c++ are we using? do we need to specify -std=c++17 in the build options?

Currently we use 11, but would prefer if we could us the newest standard that doesn't break packages, ideally 17.

**Comment by olantwin** [comment]
> any idea why this fails:
> 
> 2020-05-05@08:57:05:DEBUG:FairShip:ROOT:0: -- Performing Test found_stdstringview
> 2020-05-05@08:57:05:DEBUG:FairShip:ROOT:0: -- Performing Test found_stdstringview - Failed
> 
> CHECK_CXX_SOURCE_COMPILES("#include <string_view>
> int main() { char arr[3] = {'B', 'a', 'r'}; std::string_view strv(arr, sizeof(arr)); return 0;}" found_stdstringview)

string_view should be optional, but should lead to performance improvements.

**Comment by shir994** [comment]
@ThomasRuf When running with --MuonBack do you have this error
`Error in <TStreamerInfo::WriteBuffer>: The element FairMCPoint::fLength type 209 (double) is not supported yet`
I have tones of lines of errors for ` <TStreamerInfo::WriteBuffer>` and different classes. Although the scripts finishes OK, I guess data may be corrupted.

**Comment by ThomasRuf** [comment]
I am not so far yet with running MuonBack. However, observed a similar message when running reconstruction, see above:

Error in TStreamerInfo::Build: UpstreamTaggerHit, discarding: const double* mom, no [dimension]

**Comment by ThomasRuf** [comment]
Here my experience using a fesh ISO image and
 CXXFLAGS: "-fPIC -g -O2 -std=c++17", CMAKE_CXX_STANDARD: 17 (default-fairship.sh)

    the following system packages need to be installed:
    sudo apt-get install libglu1-mesa libglu1-mesa-dev libx11-dev libxpm-dev libxext-dev libx11-dev libxft-dev bzip2 libbz2-dev byacc krb5-user libkrb5-dev gfortran bison flex libx11-dev libxml2-dev cmake libcurl4-openssl-dev autoconf libtool libtool-bin environment-modules

    for python:
    sudo apt install python3-tk python3-pip
    sudo pip3 install matplotlib numpy scipy certifi ipython ipywidgets ipykernel notebook metakernel pyyaml sklearn

   autotools.sh
  +tag: v1.6.3

    lhapdf5:
    updated for python3, created branch v5.9.1-ship3. Don't know how to make this to work also with python2. For the moment, you need to git clone lhapdf5 and change branch manually.
    
    use ROOT v6-20-04
      +cmake_policy(SET CMP0074 OLD)
    on ubuntu, had issue that vmc was not automatically built. Modified montecarlo/CMakeLists.txt, removed -if(vmc). 
    
    geant4: git checkout geant4-10.6-release

    geant4_vmc:
    git clone https://github.com/vmc-project/geant4_vmc, used master branch
    
    FairRoot, changes committed. 
    issue on ubuntu, Protobuf not found, had to use 
      set(CMAKE_PREFIX_PATH "/usr")
      find_package(Protobuf NO_DEFAULT_PATH PATHS "/usr")
      
      
  git clone https://github.com/vmc-project/geant4_vmc

-diff --git a/protobuf.sh b/protobuf.sh
index e613463..e84e254 100644
--- a/protobuf.sh
+++ b/protobuf.sh
@@ -1,18 +1,20 @@
 package: protobuf
-version: v2.6.1
+version: v3.11.4
 source: https://github.com/google/protobuf
 build_requires:
- - autotools
+ - CMake
  - "GCC-Toolchain:(?!osx)"
-prefer_system: "(?!slc5)"
 prefer_system_check: |
   which protoc || { echo "protoc missing"; exit 1; }
   printf "#include \"google/protobuf/any.h\"\nint main(){}" | c++ -I$(brew --prefix protobuf)/include -Wno-deprecated-declarations -xc++ - -o /dev/null
 ---

-rsync -av --delete --exclude="**/.git" $SOURCEDIR/ .
-autoreconf -ivf
-./configure --prefix="$INSTALLROOT"
+cmake $SOURCEDIR/cmake                  \
+    -DCMAKE_INSTALL_PREFIX=$INSTALLROOT \
+    -Dprotobuf_BUILD_TESTS=NO           \
+    -Dprotobuf_MODULE_COMPATIBLE=YES    \
+    -Dprotobuf_BUILD_SHARED_LIBS=OFF    \
+    -DCMAKE_INSTALL_LIBDIR=lib
 make ${JOBS:+-j $JOBS}
 make install

diff --git a/openssl.sh b/openssl.sh
index ec6d930..a806a4d 100644
--- a/openssl.sh
+++ b/openssl.sh
@@ -2,9 +2,8 @@ package: OpenSSL
 version: v1.0.2o
 tag: OpenSSL_1_0_2o
 source: https://github.com/openssl/openssl
-prefer_system: (?!slc5|slc6)
 prefer_system_check: |
-  if [ `uname` = Darwin ]; then test -d `brew --prefix openssl || echo /dev/nope` || exit 1; fi; echo '#include <openssl/bio.h>' | c++ -x c++ - -I`brew --prefix openssl`/include -c -o /dev/null || exit 1; echo -e "#include <openssl/opensslv.h>\n#if OPENSSL_VERSION_NUMBER >= 0x10100000L\n#error \"System's GCC cannot be used: we need OpenSSL 1.0.x to build XrootD. We are going to compile our own version.\"\n#endif\nint main() { }" | cc -xc++ - -c -o /dev/null || exit 1
+  if [ `uname` = Darwin ]; then test -d `brew --prefix openssl || echo /dev/nope` || exit 1; fi; echo '#include <openssl/bio.h>' | c++ -x c++ - -I`brew --prefix openssl`/include -c -o /dev/null || exit 1; echo -e "#include <openssl/opensslv.h>\n#if OPENSSL_VERSION_NUMBER >= 0x10200000L\n#error \"System's GCC cannot be used: we need OpenSSL 1.0.x to build XrootD. We are going to compile our own version.\"\n#endif\nint main() { }" | cc -x c++ - -I`brew --prefix openssl`/include -c -o /dev/null || exit 1
 build_requires:
  - zlib
  - "GCC-Toolchain:(?!osx)"

**Comment by olantwin** [comment]
Could you please use code formatting? That would make it much easier to read.

> lhapdf5:
> updated for python3, created branch v5.9.1-ship3. Don't know how to make this to work also with python2. For the moment, you need to git clone lhapdf5 and change branch manually.

Here I think we can just force our lhapdf5 recipe to use python2. As we only use the python bindings during the build to download the pdf-sets (which we could even do without the python bindings using curl), we aren't constrained to match the python version used later.

The only issue could be that `slc6` `python2` might be too old, so using curl might be the most robust solution.

**Comment by ThomasRuf** [comment]
Sorry, forgot about the geant4 issue:
setenv G4PARTICLEXSDATA /media/disk0/SHiPBuild/sw/ubuntu2004_x86-64/GEANT4/geant4-10.6-release-1/share/Geant4-10.6.1/data/G4PARTICLEXS2.1
