### ISSUE TITLE
Misconfigured line endings in `veto/veto.cxx` and `passive/ShipMuonShield.cxx`

### ISSUE THREAD

**Issue by olantwin** [ShipSoft/FairShip#360]
Due to commits 8cd65a74c44a8587ec1ae2a38210de6a60a0f253 and 6fd2eabf78ba68df9380ac60ce316e65c0fc5a7f those two files are broken in my copy of the repository on lxplus, i.e. they show up as changed, but I can not check them out, stash them or do any other operations on them.

I remember that @evanherwijnen and Markus encountered this issue in the past. I'll have a look in the mailing list, whether I can reconstruct whether and how we fixed this in the past.

This is likely not an issue with the commits itself, but a symptom of misconfiguration of line-endings somewhere, resulting in git not being able to deal with this file...

Hints very much appreciated!

**Comment by tugberk92** [comment]
> Due to commits [8cd65a7](https://github.com/ShipSoft/FairShip/commit/8cd65a74c44a8587ec1ae2a38210de6a60a0f253) and [6fd2eab](https://github.com/ShipSoft/FairShip/commit/6fd2eabf78ba68df9380ac60ce316e65c0fc5a7f) those two files are broken in my copy of the repository on lxplus, i.e. they show up as changed, but I can not check them out, stash them or do any other operations on them.
> 
> I remember that @evanherwijnen and Markus encountered this issue in the past. I'll have a look in the mailing list, whether I can reconstruct whether and how we fixed this in the past.
> 
> This is likely not an issue with the commits itself, but a symptom of misconfiguration of line-endings somewhere, resulting in git not being able to deal with this file...
> 
> Hints very much appreciated!

Same as here!

**Comment by olantwin** [comment]
Closed by #367 (hopefully)
