### ISSUE TITLE
nuTau pillars and muShieldDesign 8

### ISSUE THREAD

**Issue by PlaZMaD** [ShipSoft/FairShip#397]
Hi!  I can see 
```
 c.cave.floorHeightMuonShield = 5*u.m
 if strawDesign == 10: #default one for 2018 geometry
    c.cave.floorHeightMuonShield = c.cave.floorHeightTankA  # avoid the gap, for 2018 geometry **4.2m atually**
```
in the geometry/geometry_config.py  
and
```
floor = 5. * m; //   Line 42  passive/ShipMuonShield.cxx
```
is hardcoded in the shieldDesign 8 ShipMuonShield constructor. This leads to the voume overlaps for the nutau pillars and floor volumes if muShieldDesign 8 is used.

**Comment by ThomasRuf** [comment]
I think design 8 is not generally supported, it will require its own config file:

parser.add_argument("--muShieldDesign", dest="ds",  help="5=TP muon shield, 6=magnetized hadron, 7=short magnet design, 9=optimised with T4 as constraint, 8=requires config file\
                                            ,10=with field map for hadron absorber", required=False, default=globalDesigns[default]['ds'], type=int)

supported designs are, 7 and 9.
globalDesigns = {'2016':{'dy':10.,'dv':5,'ds':7,'nud':1,'caloDesign':0,'strawDesign':4},\
                 '2018':{'dy':10.,'dv':6,'ds':9,'nud':3,'caloDesign':3,'strawDesign':10}}
default = '2018'

**Comment by PlaZMaD** [comment]
Design 8 is used for optimisation purposes and probably for short shield configuration studies. I'll prepare pull request with fixes.

**Comment by olantwin** [comment]
Is this fixed now?

**Comment by PlaZMaD** [comment]
Yeah, I'll close the issue.
