### ISSUE TITLE
Stop using future/past python modules

### ISSUE THREAD

**Issue by olantwin** [ShipSoft/FairShip#471]
These are almost always no longer needed, and a leftover of when we had to support python 2 and 3 simultaneously.

The pickler probably needs to change in a breaking way, everything else should be trivial!

**Comment by olantwin** [comment]
@egamberini Could you potentially have a look at this?

We probably also want to find a better solution than our hacked-together rootpypickler longer-term.

**Comment by egamberini** [comment]
Hi, I can have a look at it.
Do I understand correctly that:
- `from __future__` can be just dropped as we're using python3
- `from past.builtins` need some extra attention as they're using python2 features

Finally, what level of testing should I perform? Is there a comprehensive test suite for the python sources? 
Or should I just go through Sim, Reco, Ana?

Thanks

**Comment by olantwin** [comment]
Thanks a lot!

> Do I understand correctly that:
> 
>     * `from __future__` can be just dropped as we're using python3

Yes, all of those should be trivial to drop.

>     * `from past.builtins` need some extra attention as they're using python2 features

Let's discuss these on a case-by-case basis. I think we can potentially affort to break rootpyPickler, as I want to get rid of it anyway.

> Is there a comprehensive test suite for the python sources?

I wish. I hope we can build one, but right now there is 0.0% test coverage :(
Let's maybe discuss over a coffee how we could start one to at least incrementally tackle this issue.

> Or should I just go through Sim, Reco, Ana?

Making sure these run is probably as good as we can do right now. Hopefully soon we can establish some physics control plots...
