### ISSUE TITLE
empty Particles branch within reconstructed events

### ISSUE THREAD

**Issue by anupama-reghunath** [ShipSoft/FairShip#530]
This is more of a mention for a more efficient way to loop through the data:
```python
for index,event in enumerate(sTree):
            print(index)
            if hasattr(event, 'Particles'): print(len(event.Particles))
```
            
at the moment, there are events with the attribute Particles but zero entries in it. Perhaps we need to revisit the reconstruction script to ensure that 'Particles' be created only if there's a candidate.

**Comment by olantwin** [comment]
After some discussion offline, we agreed that the proper solution would be to ensure that branches such as "Particles" are:
- [ ] Consistently created
- [ ] Only contain valid entries

**Comment by olantwin** [comment]
@anupama-reghunath It seems to me that Particles should always be created when shipVertex runs, and shipDigiReco always calls it. Can you provide an example where this is not the case?

**Comment by anupama-reghunath** [comment]
You're right. Accessing t.Particles[0] directly gives segmentation faults for some events, which I wrongly interpreted as having no branch. Thanks for looking into this!

**Comment by olantwin** [comment]
> Accessing t.Particles[0] directly gives segmentation faults for some events, which I wrongly interpreted as having no branch.

This just means that that particular entry in the container does not exist. This is expected behaviour when there is no candidate in the event.

> The validity of the entries need to be revisited, I agree.

Could you please open an issue with the non-valid entries? Ideally with an example, so that we have something to start debugging from.
