### ISSUE TITLE
EvtCalc files conversion

### ISSUE THREAD

**Issue by mferril** [ShipSoft/FairShip#535]
A nicer solution would be to add a small `if __name__ == "__main__":` section to `convertEvent.py` to allow it being called directly, allowing us to do the conversion for now.

And then in `run_simScript.py` we can use the output from that script.

_Originally posted by @olantwin in https://github.com/ShipSoft/FairShip/pull/528#discussion_r1797087478_

**Comment by olantwin** [comment]
Fixed in #528
