### ISSUE TITLE
Issue with usage of ContstructedAt() 

### ISSUE THREAD

**Issue by anupama-reghunath** [ShipSoft/FairShip#569]
During testing of the usage of ConstructedAt() for MuonDIS ( In this case: `dPartDIS.ConstructedAt(nPart).Use(part)` ),  I found that while the code seems to work fine without any error, the TClonesArray() does not save the information onto the outputfile:

```
When writing:
DIS 0 mu+
DIS 1 pi-
DIS 2 gamma
DIS 3 gamma
DIS 4 proton
DIS 5 pi+
DIS 6 pi-
DIS 7 pi-
DIS 8 pi+
DIS 9 gamma
DIS 10 gamma

When reading:
 DIS Particle 0: PDG=0, Name=Rootino
 DIS Particle 1: PDG=0, Name=Rootino
 DIS Particle 2: PDG=0, Name=Rootino
 DIS Particle 3: PDG=0, Name=Rootino
 DIS Particle 4: PDG=0, Name=Rootino
 DIS Particle 5: PDG=0, Name=Rootino
 DIS Particle 6: PDG=0, Name=Rootino
 DIS Particle 7: PDG=0, Name=Rootino
 DIS Particle 8: PDG=0, Name=Rootino
 DIS Particle 9: PDG=0, Name=Rootino
 DIS Particle 10: PDG=0, Name=Rootino
```

This does not occur when using `dPartDIS[nPart]=part`

This issue was caused by commit b9309d0 : [Use ConstructedAt instead of remove pythonization for TClonesArray]

**Comment by antonioiuliano2** [comment]
Hello @anupama-reghunath,

Thank you for reporting it.
It seems to happen only for the "Particles" branch, while the "InMuon" branch is saved correctly, even if they have basically the same structure.
I cannot understand the reason.

**Comment by olantwin** [comment]
#562 is probably the best way to tackle this, moving to `std::vector<std::vector<double>>`
